### ISSUE TITLE
 "mongodb/mongodb" has invalid configuration: error loading tls configuration: failed to load TLS config: failed to load TLS cert and key: tls: failed to find any PEM data in key input

### ISSUE THREAD

**Issue by rubber-ant** [GoogleCloudPlatform/opentelemetry-operations-collector#146]
using 
```
 dpkg -l | grep ops-agent
ii  google-cloud-ops-agent             2.24.0~ubuntu20.04                amd64        Google Cloud Ops Agent
```

cluster mongo run without issue, with the following  config:
`mongodb     3950       1  0 10:43 ?        00:01:38 /usr/bin/mongod --config /etc/mongod.conf --replSet rs0 --bind_ip_all --tlsMode requireTLS --tlsCertificateKeyFile /etc/mongo/ssl/mongodb.pem --tlsCAFile /etc/mongo/ssl/ca.pem --keyFile /etc/mongo/ssl/keyfile --maxConns 1000000 --listenBacklog 4000`

inside mongo:
```
db.runCommand({getCmdLineOpts:1})
{
	"argv" : [
		"/usr/bin/mongod",
		"--config",
		"/etc/mongod.conf",
		"--replSet",
		"rs0",
		"--bind_ip_all",
		"--tlsMode",
		"requireTLS",
		"--tlsCertificateKeyFile",
		"/etc/mongo/ssl/mongodb.pem",
		"--tlsCAFile",
		"/etc/mongo/ssl/ca.pem",
		"--tlsAllowConnectionsWithoutCertificates",
		"--keyFile",
		"/etc/mongo/ssl/keyfile",
		"--maxConns",
		"1000000",
		"--listenBacklog",
		"4000"
	],
	"parsed" : {
		"config" : "/etc/mongod.conf",
		"net" : {
			"bindIp" : "*",
			"listenBacklog" : 4000,
			"maxIncomingConnections" : 1000000,
			"port" : 27017,
			"tls" : {
				"CAFile" : "/etc/mongo/ssl/ca.pem",
				"allowConnectionsWithoutCertificates" : true,
				"certificateKeyFile" : "/etc/mongo/ssl/mongodb.pem",
				"mode" : "requireTLS"
			}
		},
		"processManagement" : {
			"timeZoneInfo" : "/usr/share/zoneinfo"
		},
		"replication" : {
			"replSet" : "test0"
		},
		"security" : {
			"keyFile" : "/etc/mongo/ssl/keyfile"
```

```
ls -al /etc/mongo/ssl/
total 20
drwxr-xr-x 2 mongodb mongodb 4096 Jan 12 14:46 .
drwxr-xr-x 3 mongodb mongodb 4096 Sep  1 22:44 ..
-r--r--r-- 1 mongodb mongodb 2816 Jan 12 14:20 ca.pem
-r--r--r-- 1 mongodb mongodb   65 Jan 12 14:21 keyfile
-r--r--r-- 1 mongodb mongodb 3957 Jan 12 14:21 mongodb.pem
```
```

file /etc/mongo/ssl/*
/etc/mongo/ssl/ca.pem:      PEM certificate
/etc/mongo/ssl/keyfile:     ASCII text
/etc/mongo/ssl/mongodb.pem: PEM certificate
```

Ops-agent config:

```
cat /etc/google-cloud-ops-agent/config.yaml
metrics:
  receivers:
    mongodb:
      type: mongodb
      insecure: false
      insecure_skip_verify: false
      ca_file: /etc/mongo/ssl/ca.pem
      cert_file: /etc/mongo/ssl/mongodb.pem
      key_file: /etc/mongo/ssl/keyfile
      collection_interval: "60s"
  service:
    pipelines:
      mongo:
        receivers: [mongodb]
logging:
  receivers:
    mongodb:
      type: mongodb
      include_paths: [/mnt/mongodb/log/mongod.log]
  service:
    pipelines:
      mongo:
        receivers: [mongodb]

```

 logging works without issue but metrics  

```
systemctl status google-cloud-ops-agent-opentelemetry-collector.service
● google-cloud-ops-agent-opentelemetry-collector.service - Google Cloud Ops Agent - Metrics Agent
     Loaded: loaded (/lib/systemd/system/google-cloud-ops-agent-opentelemetry-collector.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-01-12 14:34:44 UTC; 9min ago
    Process: 19853 ExecStartPre=/opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine -service=otel -in /etc/google-cloud-ops-agent/config.yaml -logs ${LOGS_DIRECTORY} (code=exited, status=0/SUCCESS)
    Process: 19862 ExecStart=/opt/google-cloud-ops-agent/subagents/opentelemetry-collector/otelopscol --config=${RUNTIME_DIRECTORY}/otel.yaml --feature-gates=exporter.googlecloud.OTLPDirect (code=exited, status=1/FAILURE)
   Main PID: 19862 (code=exited, status=1/FAILURE)

Jan 12 14:34:44 xxxx.mongo.domain.com systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Scheduled restart job, restart counter is at 5.
Jan 12 14:34:44 xxxx.mongo.domain.com systemd[1]: Stopped Google Cloud Ops Agent - Metrics Agent.
Jan 12 14:34:44 xxxx.mongo.domain.com systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Start request repeated too quickly.
Jan 12 14:34:44 xxxx.mongo.domain.com systemd[1]: google-cloud-ops-agent-opentelemetry-collector.service: Failed with result 'exit-code'.
Jan 12 14:34:44 sxxxx.mongo.domain.com systemd[1]: Failed to start Google Cloud Ops Agent - Metrics Agent.

```

 ERRORS:

`sudo journalctl -xef | grep "otelopscol"`
`Jan 12 14:34:44 xxxx.mongo.domain.com otelopscol[19862]: 2023/01/12 14:34:44 application run finished with error: failed to get config: invalid configuration: receiver "mongodb/mongodb" has invalid configuration: error loading tls configuration: failed to load TLS config: failed to load TLS cert and key: tls: failed to find any PEM data in key input`

**Comment by ipclaudio** [comment]
**UPDATE**
issue  resolved:

I got confused about the field `key_file`  requested by the google op-agent and [keyfile](https://www.mongodb.com/docs/manual/core/security-internal-authentication/#internal-auth-keyfile) mongodb 

`key_file `should be the key use in `tlsCertificateKeyFile`. 


In my case, I was able to extract the key, running: 
`openssl pkey -in mongodb.pem -out mongodb-key.pem`


and replace this line 
       `key_file: /etc/mongo/ssl/keyfile`

with 
      `key_file: /etc/mongo/ssl/mongodb-key.pem`

this fixed the error.

Ask Google to update the documentation to clarify this point and improve the refereeing of fields:  https://cloud.google.com/monitoring/agent/ops-agent/third-party/mongodb?hl=en#mongodb-metrics

**Comment by rubber-ant** [comment]
**UPDATE**
issue  resolved:

I got confused about the field `key_file`  requested by the google op-agent and [keyfile](https://www.mongodb.com/docs/manual/core/security-internal-authentication/#internal-auth-keyfile) mongodb 

`key_file `should be the key use in `tlsCertificateKeyFile`. 


In my case, I was able to extract the key, running: 
`openssl pkey -in mongodb.pem -out mongodb-key.pem`


and replace this line 
       `key_file: /etc/mongo/ssl/keyfile`

with 
      `key_file: /etc/mongo/ssl/mongodb-key.pem`

this fixed the error.

Ask Google to update the documentation to clarify this point and improve the refereeing of fields:  https://cloud.google.com/monitoring/agent/ops-agent/third-party/mongodb?hl=en#mongodb-metrics

**Comment by braydonk** [comment]
Hi @rubber-ant, thanks for bringing this to our attention! I've raised the issue with our technical writing team and we'll work with them to update the docs and help others avoid this confusion.

I'll close this issue for now since it's resolved. Thanks!
