### ISSUE TITLE
Circular reference in Windows 'make.ps1 New-MSI' command.

### ISSUE THREAD

**Issue by BarraccaJ** [GoogleCloudPlatform/opentelemetry-operations-collector#155]
When executing the [Windows makefile](https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/9bfb379327ffc7770ee8d44eeff4c871f4a98d97/.build/msi/make.ps1#L60), an error is created indicating the .msi creation process needs access to the exe.

```C:\otel\.build\msi\google-cloud-metrics-agent.wxs(28) : error LGHT0103 : The system cannot find the file './bin/google-cloud-metrics-agent_windows_amd64.exe'.```

[Looks like part of the service definition is what is causing the problem.](https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/9bfb379327ffc7770ee8d44eeff4c871f4a98d97/.build/msi/google-cloud-metrics-agent.wxs#L28)

Unfortunately the reason I am executing the makefile is as a means to create the most up-to-date .exe, creating somewhat of a circular dependency.

**Comment by braydonk** [comment]
Hi @BarraccaJ,

We have not been maintaining the MSI installation of this project for some time; there is a good chance this is simply bit-rot from the last few years. I will discuss with the team what action we'll take, either fixing this or simply removing it from the Makefile. Thanks for bringing this to our attention!
