### ISSUE TITLE
header-checker-lint check fails to detect `Apache-2.0` license

### ISSUE THREAD

**Issue by qingling128** [GoogleCloudPlatform/opentelemetry-operations-collector#44]
header-checker-lint check was added by https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/pull/42. It seems like the check only runs on files that are modified by a PR: https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/pull/43#issuecomment-824473435 so it turned out that a handful of files in master branch actually do not pass this check.

![image](https://user-images.githubusercontent.com/5287526/115644553-cbcb1e00-a2ec-11eb-8195-22a6bd7e81f8.png)

Looking a bit closer into the check:

We have defined `Apache-2.0` as allowed licenses in https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/master/.github/header-checker-lint.yml This looks correct according to the tool's documentation at https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/master/.github/header-checker-lint.yml

```
allowedLicenses:
  - Apache-2.0
sourceFileExtensions:
  - go
  - ps1
  - sh
```

The actual code in that `header-checker-lint.yml` uses the following pattern to match `Apache-2.0` license (https://github.com/googleapis/repo-automation-bots/blob/master/packages/header-checker-lint/src/header-parser.ts#L24):

```
const APACHE2_REGEX = new RegExp(
  'Licensed under the Apache License, Version 2.0'
);
```

But the exact pattern does exist in the file:

![image](https://user-images.githubusercontent.com/5287526/115644686-fddc8000-a2ec-11eb-8af9-bb75ffd49f10.png)

**Comment by punya** [comment]
I believe the problem is with the copyright line, not the license. It expects `Google LLC`, not `Google Inc.`. https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/164/files is another example of the same problem.

**Comment by qingling128** [comment]
> I believe the problem is with the copyright line, not the license. It expects `Google LLC`, not `Google Inc.`. https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/164/files is another example of the same problem.

That makes total sense. Thanks Punya for pointing us at the right direction. Sent a PR for the fix.
